### ISSUE TITLE
DiffCover / Jacoco issue in Bitrise Ci

### ISSUE THREAD

**Issue by afaucogney** [Bachmann1234/diff_cover#155]
I succeed to run diff_cover on my macOS, but it does failed on the Bitrise Ci server:

Here is the issue:
```
Traceback (most recent call last):
  File "/usr/local/bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/diff_cover_tool.py", line 220, in main
    diff_range_notation=arg_dict['diff_range_notation']
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/diff_cover_tool.py", line 178, in generate_coverage_report
    reporter.generate_report(output_file)
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/report_generator.py", line 254, in generate_report
    report = template.render(self._context())
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/report_generator.py", line 303, in _context
    context = super(TemplateReportGenerator, self).report_dict()
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/report_generator.py", line 182, in report_dict
    src: self._src_path_stats(src) for src in self.src_paths()
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/report_generator.py", line 84, in src_paths
    return {src for src, summary in self._diff_violations().items()
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    for src_path in self._diff.src_paths_changed()
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/diff_reporter.py", line 147, in src_paths_changed
    diff_dict = self._git_diff()
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/diff_reporter.py", line 196, in _git_diff
    for diff_str in self._get_included_diff_results():
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/diff_reporter.py", line 169, in _get_included_diff_results
    included = [self._git_diff_tool.diff_committed(self._compare_branch)]
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/git_diff.py", line 54, in diff_committed
    '-U0'
  File "/usr/local/lib/python2.7/dist-packages/diff_cover/command_runner.py", line 43, in execute
    raise CommandError(stderr)
diff_cover.command_runner.CommandError: fatal: ambiguous argument 'origin/develop...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Any idea what could be wrong ?

**Comment by afaucogney** [comment]
I use this configuration:
```
  diff-cover "$NEWSFEED_JACOCO_REPORT" \
    --compare-branch=origin/develop \
    --html-report "$NEWSFEED_DIFF_COVER_REPORT" \
    --src-roots "$NEWSFEED_SRC"
```

**Comment by Bachmann1234** [comment]
Any chance you are working from a shallow clone of the repo? That would explain it.

**Comment by Bachmann1234** [comment]
I would also try to run the diff outside of diff cover. Just with a vanilla git command

`git diff origin/develop...head`

**Comment by afaucogney** [comment]
@Bachmann1234 That was the case, I did a git diff in the meantime, and "tada", it doesn't work too.

So for others in my case, you need to fetch the develop branch in your ci runtime, by:

`git fetch origin develop` then the branch is available so diff-cover can work.
