### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 438: invalid start byte

### ISSUE THREAD

**Issue by realhac** [Bachmann1234/diff_cover#167]
diff-cover generate diff report with --src-roots, the follwing exception occured due to differrent source code encoding format in projects:
Traceback (most recent call last):
  File "/usr/local/python3/bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 232, in main
    percent_covered = generate_coverage_report(
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 195, in generate_coverage_report
    reporter.generate_report(output_file)
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 251, in generate_report
    report = template.render(self._context())
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 300, in _context
    context = super().report_dict()
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 183, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 183, in <dictcomp>
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 343, in _src_path_stats
    formatted_snippets = Snippet.load_formatted_snippets(
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/snippets.py", line 175, in load_formatted_snippets
    snippet_list = cls.load_snippets(src_path, violation_lines)
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/snippets.py", line 198, in load_snippets
    contents = src_file.read()
  File "/usr/local/python3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 438: invalid start byte.

**Comment by Bachmann1234** [comment]
Can you give me a bit more info to reproduce? What encoding is your source files?

**Comment by realhac** [comment]
currently, in a project,  some source files are "fileencoding=utf-8", and others are "fileencoding=latin1".

**Comment by Bachmann1234** [comment]
Hmm, multiple encodings.

Kk, I'll do some thinking. I got a couple ideas.

**Comment by Bachmann1234** [comment]
@realhac I took a stab at fixing this in a way that would require no change on your side. Let me know if 4.2.0 https://pypi.org/project/diff-cover/4.2.0/ works for you. 

If not I think I will have to go in and allow users to specify what encodings I should be expecting.

**Comment by realhac** [comment]
sorry for late. It seems not well.
Traceback (most recent call last):
  File "/usr/local/python3/bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 232, in main
    percent_covered = generate_coverage_report(
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 195, in generate_coverage_report
    reporter.generate_report(output_file)
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 251, in generate_report
    report = template.render(self._context())
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 300, in _context
    context = super().report_dict()
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 183, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 183, in <dictcomp>
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/report_generator.py", line 343, in _src_path_stats
    formatted_snippets = Snippet.load_formatted_snippets(
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/snippets.py", line 176, in load_formatted_snippets
    snippet_list = cls.load_snippets(src_path, violation_lines)
  File "/usr/local/python3/lib/python3.9/site-packages/diff_cover/snippets.py", line 206, in load_snippets
    contents = src_file.read()
  File "/usr/local/python3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 2936: invalid continuation byte

**Comment by Bachmann1234** [comment]
Alrighty, I'll take another stab at this over the weekend.

**Comment by Bachmann1234** [comment]
Ok, I think I got at least this issue with https://pypi.org/project/diff-cover/4.2.1/

I was a bit lazy last time and did not reproduce with a test. 

I am not 100% sure if I have solved this entirely. An example project to try would verify that. But how about you give 4.2.1 a shot and see if it works

**Comment by realhac** [comment]
It looks like you have resolved this issue, thanks.

Total:   12 lines
Missing: 10 lines
Coverage: 16%

**Comment by Bachmann1234** [comment]
woot!
