### ISSUE TITLE
Python3.5+Ubuntu16.04.5 LTS

### ISSUE THREAD

**Issue by andriitc** [Bachmann1234/diff_cover#174]
Hi folks!
How are you ? 
I have a small problem:

```
# diff-cover
Traceback (most recent call last):
  File "/usr/local/bin/diff-cover", line 7, in <module>
    from diff_cover.diff_cover_tool import main
  File "/usr/local/lib/python3.5/dist-packages/diff_cover/diff_cover_tool.py", line 18, in <module>
    from diff_cover.report_generator import (
  File "/usr/local/lib/python3.5/dist-packages/diff_cover/report_generator.py", line 7, in <module>
    from jinja2_pluralize import pluralize_dj
  File "/usr/local/lib/python3.5/dist-packages/jinja2_pluralize/__init__.py", line 7, in <module>
    import inflect
  File "/usr/local/lib/python3.5/dist-packages/inflect.py", line 93
    return f"(?:{s})"
                    ^
SyntaxError: invalid syntax
```

Can you help me ?

**Comment by Bachmann1234** [comment]
Howdy! 

So here is what I think is happening. This project depends on Jinja2 and Jinja2 pluralize both support python3.5

Those projects depend on https://github.com/jaraco/inflect/ which does _not_ support python3.5. 

Last week inflect made a release that uses fstrings. A feature added to python in version 3.6. 

SO I think if you uninstall inflect. Then install inflect==5.0.2 this should work again. 

This evening I will package a release to attempt and fix this. Though since python3.5 has been end of lifed I will likely be dropping support for it fairly soon.

**Comment by andriitc** [comment]
@Bachmann1234 Thank you for replay.

What I have now:
```
~# pip3 show inflect
---
Metadata-Version: 2.1
Name: inflect
Version: 5.0.2
Summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
Home-page: https://github.com/jaraco/inflect
Author: Paul Dyson
Author-email: pwdyson@yahoo.com
Installer: pip
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3 :: Only
  Natural Language :: English
  Operating System :: OS Independent
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Text Processing :: Linguistic
```
and 

```
~# diff-cover
Traceback (most recent call last):
  File "/usr/local/bin/diff-cover", line 7, in <module>
    from diff_cover.diff_cover_tool import main
  File "/usr/local/lib/python3.5/dist-packages/diff_cover/diff_cover_tool.py", line 18, in <module>
    from diff_cover.report_generator import (
  File "/usr/local/lib/python3.5/dist-packages/diff_cover/report_generator.py", line 7, in <module>
    from jinja2_pluralize import pluralize_dj
  File "/usr/local/lib/python3.5/dist-packages/jinja2_pluralize/__init__.py", line 7, in <module>
    import inflect
  File "/usr/local/lib/python3.5/dist-packages/inflect.py", line 1455
    pl_sb_postfix_adj: Dict[str, str] = {}
                     ^
SyntaxError: invalid syntax
```

**Comment by Bachmann1234** [comment]
Looks like another python 3.6 feature. Looking at their changelog  https://github.com/jaraco/inflect/blob/main/CHANGES.rst#v400 they dropped 3.5 support in V4.0.0

So maybe try out v3.0.2

**Comment by andriitc** [comment]
It works . Thank you !!
```
# diff-cover
usage: diff-cover [-h]
                  [--html-report FILENAME | --json-report FILENAME | --markdown-report FILENAME]
                  [--external-css-file FILENAME] [--compare-branch BRANCH]
                  [--fail-under SCORE] [--ignore-staged] [--ignore-unstaged]
                  [--exclude EXCLUDE [EXCLUDE ...]]
                  [--src-roots DIRECTORY [DIRECTORY ...]]
                  [--diff-range-notation RANGE_NOTATION] [--version]
                  [--ignore-whitespace]
                  coverage_xml [coverage_xml ...]
diff-cover: error: the following arguments are required: coverage_xml
```

```
# pip3 show inflect
---
Metadata-Version: 2.1
Name: inflect
Version: 3.0.2
Summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
Home-page: https://github.com/jazzband/inflect
Author: Paul Dyson
Author-email: pwdyson@yahoo.com
Installer: pip
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: importlib-metadata
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Natural Language :: English
  Operating System :: OS Independent
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Text Processing :: Linguistic
```

**Comment by Bachmann1234** [comment]
kk, ill publish a fix in the package today.

**Comment by Bachmann1234** [comment]
https://pypi.org/project/diff-cover/4.2.2/ should work without needing to install inflect yourself

**Comment by andriitc** [comment]
Yes, it works !

**Comment by The-Compiler** [comment]
If you have an up-to-date pip, it should take care of this automatically:

```
─[florian@aragog]──[~/tmp]──[21-03-08]──[11:34]────┄
$ python3.5 -m venv .venv

─[florian@aragog]──[~/tmp]──[21-03-08]──[11:34]────┄
$ .venv/bin/pip install diff-cover==4.2.1
[...]
Installing collected packages: chardet, MarkupSafe, Jinja2, zipp, importlib-metadata, pluggy, pygments, inflect, jinja2-pluralize, diff-cover
Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 chardet-4.0.0 diff-cover-4.2.1 importlib-metadata-2.1.1 inflect-3.0.2 jinja2-pluralize-0.3.0 pluggy-0.13.1 pygments-2.8.1 zipp-1.2.0
```

(Note how inflect-3.0.2 got installed despite me installing the older 4.2.1 version of diff-cover)

Since `inflect` is now pinned in `setup.py`, this change forces an older version of `inflect` onto everyone who installs `diff_cover`.

**Comment by Bachmann1234** [comment]
Point is somewhat moot. I'm overdue for dropping 35 and adding 39. I'll do that this week and drop the pin.

**Comment by Bachmann1234** [comment]
@The-Compiler https://pypi.org/project/diff-cover/5.0.0/ is out and the pin is no longer there. 

I understand your greater point that the pin was never really necessary assuming the user was using the latest `pip` but like I said, I was overdue on dropping 3.5
