### ISSUE TITLE
Broken syntax due to jinja release

### ISSUE THREAD

**Issue by ganeshramc** [Bachmann1234/diff_cover#188]
I'm using the version 4.2.3 in my jenkins pipeline. It looks like there was a new jinja2 release which is making diff_cover fail.
Release: https://github.com/pallets/jinja/releases/tag/3.0.0
Stacktrace:

```
[2021-05-11T22:05:03.354Z] Traceback (most recent call last):
[2021-05-11T22:05:03.354Z]   File "/usr/local/bin/diff-cover", line 7, in <module>
[2021-05-11T22:05:03.354Z]     from diff_cover.diff_cover_tool import main
[2021-05-11T22:05:03.354Z]   File "/usr/local/lib/python3.5/dist-packages/diff_cover/diff_cover_tool.py", line 18, in <module>
[2021-05-11T22:05:03.354Z]     from diff_cover.report_generator import (
[2021-05-11T22:05:03.354Z]   File "/usr/local/lib/python3.5/dist-packages/diff_cover/report_generator.py", line 6, in <module>
[2021-05-11T22:05:03.354Z]     from jinja2 import Environment, PackageLoader
[2021-05-11T22:05:03.354Z]   File "/usr/local/lib/python3.5/dist-packages/jinja2/__init__.py", line 5, in <module>
[2021-05-11T22:05:03.354Z]     from .bccache import BytecodeCache
[2021-05-11T22:05:03.354Z]   File "/usr/local/lib/python3.5/dist-packages/jinja2/bccache.py", line 61
[2021-05-11T22:05:03.354Z]     self.code: t.Optional[CodeType] = None
```

**Comment by Bachmann1234** [comment]
I would try upgrading your python or pinning jinja down. 

Jinja2 version drops support for python 3.5. I suspect they are leveraging features introduced in 3.6 and beyond now.

https://jinja.palletsprojects.com/en/3.0.x/changes/

**Comment by ganeshramc** [comment]
Ahh! Okay thanks I'll give that a try.
