### ISSUE TITLE
diff-cover fails if file path starts with space

### ISSUE THREAD

**Issue by tkukushkin** [Bachmann1234/diff_cover#239]
This is not a very real situation, but we had a diff-cover on one of the repositories started to crash and after digging in the code I found that one of the file paths in the diff was determined to be an empty string.

```diff
diff --git a/ tox.ini b/ tox.ini
new file mode 100644
```

Regex that parses such lines takes all before first space or new line:
```regex
^diff --git "?a/.*"? "?b/([^ \n"]*)"?
```

Traceback:
```python
Traceback (most recent call last):
  File ".../bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File ".../lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 260, in main
    percent_covered = generate_coverage_report(
  File ".../lib/python3.9/site-packages/diff_cover/diff_cover_tool.py", line 219, in generate_coverage_report
    reporter.generate_report(output_file)
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 256, in generate_report
    report = template.render(self._context())
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 305, in _context
    context = super().report_dict()
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 187, in report_dict
    src_stats = {src: self._src_path_stats(src) for src in self.src_paths()}
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 84, in src_paths
    for src, summary in self._diff_violations().items()
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    self._diff_violations_dict = {
  File ".../lib/python3.9/site-packages/diff_cover/report_generator.py", line 178, in <dictcomp>
    self._violations.violations(src_path),
  File ".../lib/python3.9/site-packages/diff_cover/violationsreporters/violations_reporter.py", line 260, in violations
    self._cache_file(src_path)
  File ".../lib/python3.9/site-packages/diff_cover/violationsreporters/violations_reporter.py", line 219, in _cache_file
    line_nodes = self.get_src_path_line_nodes_cobertura(
  File ".../lib/python3.9/site-packages/diff_cover/violationsreporters/violations_reporter.py", line 112, in get_src_path_line_nodes_cobertura
    classes = self._get_classes(xml_document, src_path)
  File ".../lib/python3.9/site-packages/diff_cover/violationsreporters/violations_reporter.py", line 73, in _get_classes
    src_rel_path = self._to_unix_path(GitPathTool.relative_path(src_path))
  File ".../lib/python3.9/site-packages/diff_cover/git_path.py", line 45, in relative_path
    return os.path.relpath(git_diff_path, root_rel_path)
  File ".../lib/python3.9/posixpath.py", line 453, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
```

**Comment by Bachmann1234** [comment]
ah, sounds like we need to strip some spaces. should not be too hard to fix. Thanks for the report.

**Comment by tkukushkin** [comment]
I didn't describe it well, the file actually has a space at the beginning of the name, this is not git diff formatting.

**Comment by Bachmann1234** [comment]
oh, thats more interesting!

**Comment by kasium** [comment]
@Bachmann1234 do you take a look or should I try to support?

**Comment by Bachmann1234** [comment]
@kasium If you are available and interested go ahead. I was not going to get to it till next week

**Comment by kasium** [comment]
I'll take a look.
@tkukushkin So, one file you changed/created started with a space, right?

**Comment by tkukushkin** [comment]
Yes. It was an accident, but it was pretty hard to find the reason

**Comment by kasium** [comment]
Reproducible example:

1. ``python -m pytest --cov --cov-report=xml tests`` --> generate a coverage.xml
2. Rename ``verify.sh`` to `` verify.sh``
3. ``diff-cover coverage.xml --include-untracked``

**Comment by Bachmann1234** [comment]
@tkukushkin try https://pypi.org/project/diff-cover/6.3.2/ and see if that works for you. Should include @kasium 's fix.

**Comment by kasium** [comment]
@Bachmann1234 maybe here is some confusion, The fix I just pushed was for a special case when including untracked files. In the stack trace of @tkukushkin you can see that this happens somewhere in the XML report handler. I guess these are not related. You might want to adjust the change log.

**Comment by Bachmann1234** [comment]
My bad. Bouncing between a few things and connected the two. I'll update the changelog now. 


I won't bother to yank the release. Sorry for the confusion.

**Comment by kasium** [comment]
Still a valid fix for a corner case. I guess a yank is not needed. Thanks

**Comment by Bachmann1234** [comment]
So @tkukushkin 6.3.2 wont fix anything for you. I might be able to look into this tonight but sometime next week is more likely

**Comment by Bachmann1234** [comment]
Potential fix here https://github.com/Bachmann1234/diff_cover/pull/245 still need to write a test https://github.com/Bachmann1234/diff_cover/pull/245

**Comment by Bachmann1234** [comment]
Ok, @tkukushkin give https://pypi.org/project/diff-cover/6.3.3/ a shot and let me know if that works for ya

**Comment by tkukushkin** [comment]
Checked 6.3.3 and everything is fine, no more errors. Thanks!
