### ISSUE TITLE
diff-cover breaks in GitLab CI due to strange git failure

### ISSUE THREAD

**Issue by warsaw** [Bachmann1234/diff_cover#287]
I'm working on a [new PR for flufl.enum](https://gitlab.com/warsaw/flufl.enum/-/merge_requests/3), and as part of the CI, I run [diff-cover](https://gitlab.com/warsaw/flufl.enum/-/merge_requests/3/diffs#61be067c7cf3bdbf8a6b021a2b5167eb30612d0c_6_16).  This works perfectly fine on my local dev machine, but breaks in CI when run on the ["active" Python CI image](https://gitlab.com/python-devs/ci-images/container_registry/48153).  To make matters worse, it only fails when run on the GitLab platform; it succeeds when I run the same set of command in my local Docker image.

[Here is the relevant lines](https://gitlab.com/warsaw/flufl.enum/-/jobs/2924304157#L219) in the job where you can see diff-cover fail for Python 3.7.  For clarity, the traceback says:

```
py37 run-test: commands[3] | -diff-cover coverage.xml
Traceback (most recent call last):
  File "/builds/warsaw/flufl.enum/.tox/py37/bin/diff-cover", line 8, in <module>
    sys.exit(main())
  File "/builds/warsaw/flufl.enum/.tox/py37/lib/python3.7/site-packages/diff_cover/diff_cover_tool.py", line 258, in main
    GitPathTool.set_cwd(directory)
  File "/builds/warsaw/flufl.enum/.tox/py37/lib/python3.7/site-packages/diff_cover/git_path.py", line 33, in set_cwd
    cls._root = cls._git_root()
  File "/builds/warsaw/flufl.enum/.tox/py37/lib/python3.7/site-packages/diff_cover/git_path.py", line 65, in _git_root
    git_root = execute(command)[0]
  File "/builds/warsaw/flufl.enum/.tox/py37/lib/python3.7/site-packages/diff_cover/command_runner.py", line 45, in execute
    raise CommandError(stderr)
diff_cover.command_runner.CommandError: fatal: detected dubious ownership in repository at '/builds/warsaw/flufl.enum'
To add an exception for this directory, call:
	git config --global --add safe.directory /builds/warsaw/flufl.enum
```

Now things get strange because I actually [added the referenced](https://gitlab.com/warsaw/flufl.enum/-/merge_requests/3/diffs#587d266bb27a4dc3022bbed44dfa19849df3044c_0_16) `git config` command in my `.gitlab-ci.yml` file:

```
    - git config --global --add safe.directory $CI_PROJECT_DIR
```

and you can see in the full Linux job output that `$CI_PROJECT_DIR` is `/builds/warsaw/flufl.enum`.   For grins, I tried changing the directory for `safe.directory` to various things like `pwd`, hardcoded `/builds/warsaw/flufl.enum`, and even `'*'` and none of those help.

I get the same failure when I run `diff-cover` for any of my supported Python versions (3.7 - 3.11).

I wonder, is it possible that `diff-cover` is using a different git config file?  But then why would `--global` not fix that?  Is there any way to further debug the git commands that `diff-cover` is using to try to figure out why the underlying `git` command is failing with this error?

**Comment by warsaw** [comment]
The problem is that, yes you need to `git config --global --add safe.directory` but you *also* need to be sure that `$HOME` is passed into the tox execution environment.  Otherwise the `git config --global` outside of tox doesn't match up with the `git config --global` that `diff-cover` implicitly finds when it runs `git`.

I'm not quite sure why `passenv` didn't work in my `tox.ini`, but I can use `TOX_TESTENV_PASSENV=HOME tox` in my `.gitlab-ci.yml` file and it does the trick.

Closing, but hopefully this will be helpful to someone, decades from now, encountering the same weird problem.
